- name: all
  hosts: all
  gather_facts: false
  sudo: true
  roles:
    - disable-require-tty
    - selinux
    - shared-hosts-file
    - {role: influxdb-telegraf, tags: telegraf}
  tags:
    - common

- name: influxdb
  hosts: influxdb
  gather_facts: false
  sudo: true
  roles:
    - influxdb
  tags:
    - influxdb

- name: grafana
  hosts: grafana
  gather_facts: false
  sudo: true
  roles:
    - grafana
  tags:
    - grafana
