- name: all
  hosts: all
  gather_facts: false
  sudo: true
  roles:
    - disable-require-tty
    - selinux
    - shared-hosts-file
  tags:
    - common

- name: influxdb
  hosts: influxdb
  gather_facts: false
  serial: 1
  sudo: true
  roles:
    - influxdb
  tags:
    - influxdb

- name: influxdb telegraf
  hosts: all
  gather_facts: false
  sudo: true
  roles:
    - influxdb-telegraf
  tags:
    - telegraf

- name: grafana
  hosts: grafana
  gather_facts: false
  sudo: true
  roles:
    - grafana
  tags:
    - grafana
