- name: influxdb
  hosts: influxdb
  gather_facts: true
  become: true
  roles:
    - influxdb
  tags:
    - influxdb

- name: influxdb-relay
  hosts: influxdb-relay
  gather_facts: true
  become: true
  roles:
    - influxdb-relay
  tags:
    - influxdb-relay

- name: influxdb telegraf
  hosts: telegraf
  gather_facts: true
  become: true
  roles:
    - influxdb-telegraf
  tags:
    - telegraf

- name: influxdb kapacitor
  hosts: kapacitor
  gather_facts: true
  become: true
  roles:
    - influxdb-kapacitor
  tags:
    - kapacitor

- name: grafana
  hosts: grafana
  gather_facts: true
  become: true
  roles:
    - grafana
  tags:
    - grafana
