- name: influxdb
  hosts: influxdb
  gather_facts: false
  serial: 1
  sudo: true
  roles:
    - influxdb
  tags:
    - influxdb

- name: influxdb telegraf
  hosts: all
  gather_facts: false
  sudo: true
  roles:
    - influxdb-telegraf
  tags:
    - telegraf

- name: influxdb kapacitor
  hosts: kapacitor
  gather_facts: false
  sudo: true
  roles:
    - influxdb-kapacitor
  tags:
    - kapacitor

- name: grafana
  hosts: grafana
  gather_facts: false
  sudo: true
  roles:
    - grafana
  tags:
    - grafana
