- name: download influxdb
  get_url:
    url: https://s3.amazonaws.com/influxdb/influxdb-0.9.3-1.x86_64.rpm
    dest: /opt/

- name: install influxdb
  yum: name=/opt/influxdb-0.9.3-1.x86_64.rpm

- name: setup influxdb config
  template:
    src: influxdb.conf
    dest: /etc/opt/influxdb/influxdb.conf
  notify: restart influxdb

- name: setup influxdb environment file
  template:
    src: influxdb_env
    dest: /etc/default/influxdb
  notify: restart influxdb

- name: install influxdb service file
  template: src=influxdb.service dest=/usr/lib/systemd/system/influxdb.service
  register: service

- name: reload service files
  shell: systemctl daemon-reload
  when: service.changed
  notify: restart influxdb

- name: start and enable influxdb
  service: name=influxdb state=started enabled=yes
