- name: install consul binary
  unarchive: src=consul-0.5.2.tar.gz dest=/usr/bin

- name: create consul directory structure
  file: path={{item}} state=directory
  with_items:
    - /opt/consul/data
    - /etc/consul/consul.d
    - /var/log/consul

- name: consul config file
  template:
    src: consul.json.j2
    dest: /etc/consul/consul.json
    mode: 0755
  notify: restart consul

- name: install consul service file
  template: src=consul.service dest=/usr/lib/systemd/system/consul.service
  register: service

- name: reload service files
  shell: systemctl daemon-reload
  when: service.changed

- name: start and enable consul server
  service: name=consul state=started enabled=yes
